spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud-user
    username: postgres
    password: edwaldo
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
  rabbitmq:
    host: localhost
    port: 5672

jwt:
  secretKey: "Y9+Sqz0qYeUloLQ5Jtb4u/7M2vQMoAGjIbSNzj3N5Dw="

logging.level.org.hibernate.SQL: debug
